### ISSUE TITLE
Colorpicker does not dismiss/close when I click outside of it

### ISSUE THREAD

**Issue by blackbaud-conorwright** [blackbaud/skyux-colorpicker#27] opened 2019-10-31 21:55 UTC
### Expected behavior
When I click on the page or some other element outside of the colorpicker dropdown, the colorpicker dropdown should close.

### Actual behavior
The colorpicker dropdown remains open.

### Steps to reproduce
1. Click to open the colorpicker
2. Click on the page or somewhere else outside of the colorpicker and its dropdown.
3. See that the dropdown is still open/expanded

### Severity
Medium - This isn't the worst because they can hit close, but it is really jarring and sometimes covers other functionality the user is trying to interact with until they go and hit close explicitly.

### Impact
Anywhere colorpickers are used, so pretty wide. This also seems like a pretty common expectation for this kind of expandable component.

You can use the colorpicker demo to see the issue:
https://stackblitz.com/run?file=src/app/demo/colorpicker-reactive-demo.component.html

**Comment by Blackbaud-SteveBrush** [comment] 2019-11-04 19:01
Closing since this is by design; @Blackbaud-ToddRoberts can confirm.

**Closed by Blackbaud-SteveBrush** 2019-11-04 19:01 UTC
